services:
  postgres:
    image: postgres:15-alpine
    container_name: teclingo_postgres_dev
    environment:
      POSTGRES_DB: teclingo_db
      POSTGRES_USER: teclingo_user
      POSTGRES_PASSWORD: MiPasswordLocal123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: